Feat/user accounts info
JongHyeok-Park/shokey pull request #32
Opened 2024-08-27 00:51 UTC by hanguswls

## 시나리오 테스트
| 테스트 케이스 제목 | 시나리오 흐름 | 입력 | 사전조건 | 기대결과 |
|------------------|--------------|------|----------|----------|
| 계좌 정보가 없는 사용자의 계좌 등록 | 1. 로그인 상태에서 계좌 정보 페이지 접근<br>2. '계좌 등록' 버튼 클릭<br>3. 모든 필드 입력<br>4. '계좌 등록' 버튼 클릭 | - 은행: "신한은행"<br>- 계좌번호: "123-456-789" | - 로그인 상태: 로그인<br>- 계좌 등록 여부: 미등록<br>- 잔액: 0원 | - 계좌 정보가 등록됨<br>- '계좌 정보가 수정되었습니다.' 알림 표시<br>- 모달 창 닫힘<br>- 계좌 정보 페이지에 등록된 정보 표시 |
| 계좌 정보 수정 | 1. 로그인 상태에서 계좌 정보 페이지 접근<br>2. '계좌 수정' 버튼 클릭<br>3. 일부 필드 수정<br>4. '계좌 수정' 버튼 클릭 | - 은행: "우리은행"<br>- 계좌번호: 변경 없음 | - 로그인 상태: 로그인<br>- 계좌 등록 여부: 등록<br>- 기존 은행: "신한은행"<br>- 기존 계좌번호: "123-456-789"<br>- 잔액: 10,000원 | - 계좌 정보가 수정됨<br>- 모달 창 닫힘<br>- 계좌 정보 페이지에 수정된 정보 표시 |
| 입금 기능 | 1. 로그인 상태에서 계좌 정보 페이지 접근<br>2. '입금' 버튼 클릭<br>3. 입금액 입력<br>4. '입금' 버튼 클릭 | - 입금액: 5,000원 | - 로그인 상태: 로그인<br>- 계좌 등록 여부: 등록<br>- 기존 잔액: 10,000원 | - 입금 처리됨<br>- 모달 창 닫힘<br>- 계좌 정보 페이지에 갱신된 잔액(15,000원) 표시 |
| 출금 기능 | 1. 로그인 상태에서 계좌 정보 페이지 접근<br>2. '출금' 버튼 클릭<br>3. 출금액 입력<br>4. '출금' 버튼 클릭 | - 출금액: 3,000원 | - 로그인 상태: 로그인<br>- 계좌 등록 여부: 등록<br>- 기존 잔액: 15,000원 | - 출금 처리됨<br>- 모달 창 닫힘<br>- 계좌 정보 페이지에 갱신된 잔액(12,000원) 표시 |
| 잔액 초과 출금 시도 | 1. 로그인 상태에서 계좌 정보 페이지 접근<br>2. '출금' 버튼 클릭<br>3. 잔액을 초과하는 출금액 입력<br>4. '출금' 버튼 클릭 | - 출금액: 20,000원 | - 로그인 상태: 로그인<br>- 계좌 등록 여부: 등록<br>- 기존 잔액: 12,000원 | - 오류 메시지 표시<br>- 잔액 변동 없음 |

2024-08-27 01:28 UTC, JongHyeok-Park requested changes

2024-08-27 01:28 UTC, JongHyeok-Park commented on src/routes/ViewMyUser.jsx
> +      return;
삭제

2024-08-27 01:28 UTC, JongHyeok-Park commented on src/hooks/useAccounts.js
> +  const fetchAccounts = async () => {
이거 함수 이름은 좀 다시 고민해보는게 좋을듯

2024-08-27 01:28 UTC, JongHyeok-Park commented on src/hooks/useAccounts.js
> +  const fetchBalance = async() => {
얘도 이름 고민

2024-08-27 01:28 UTC, JongHyeok-Park commented on src/hooks/useAccounts.js
> +  const handleRegisterAccounts = async (e) => {
이벤트 이름 추가하기

2024-08-27 01:28 UTC, JongHyeok-Park commented on src/hooks/useAccounts.js
> +  const handleRegisterAccounts = async (e) => {
나머지 밑에 있는 애들도

2024-08-27 12:42 UTC, hanguswls commented on src/routes/ViewMyUser.jsx
> +      return;
- [x] **삭제 완료**

2024-08-28 07:47 UTC, JongHyeok-Park approved these changes

2024-08-28 07:53 UTC, merged